title: go-scope-config
description: A simple and flexible way to load configurations based on an environment scope (e.g., dev, prod, staging).
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-gist
  - jekyll-mentions

exclude:
  - vendor/
  - node_modules/
  - examples/
  - mocks/
  - go.mod
  - go.sum
  - go.work
  - go.work.sum
  - Taskfile.yml
  - config_loader_test.go
  - autoload/autoload_test.go
  - Makefile
  - .golangci.yml
  - .mockery.yaml

include:
  - README.md
